name: ACR_Deployment_Pipeline

trigger: none

pool:
  name: ACR-Agent-Pool

stages:
- stage: Deploy_Infrastructure
  displayName: 'Deploy ACR Infrastructure'
  jobs:
  - job: Terraform_Deploy
    displayName: 'Deploy ACR with Terraform'
    steps:
    - script: |
        cd "Deploy ACR/terraform"
        terraform init
      displayName: 'Initialize Terraform'
    
    - script: |
        cd "Deploy ACR/terraform"
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'
    
    - script: |
        cd "Deploy ACR/terraform"
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'

- stage: Build_And_Push_Image
  displayName: 'Build and Push Docker Image'
  dependsOn: Deploy_Infrastructure
  jobs:
  - job: Docker_Build
    displayName: 'Build and Push Python Image'
    steps:
    - script: |
        cd "Deploy ACR/terraform"
        terraform init
        ACR_NAME=$(terraform output -raw acr_name)
        ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)
        echo "ACR Name: $ACR_NAME"
        echo "ACR Login Server: $ACR_LOGIN_SERVER"
        
        # Login to ACR
        az acr login --name $ACR_NAME
        
        # Build Docker image
        cd ../app
        docker build -t python-flask-app .
        
        # Tag and push
        docker tag python-flask-app ${ACR_LOGIN_SERVER}/python-flask-app:v1
        docker push ${ACR_LOGIN_SERVER}/python-flask-app:v1
        
        # Verify
        az acr repository list --name $ACR_NAME --output table
        az acr repository show-tags --name $ACR_NAME --repository python-flask-app --output table
      displayName: 'Build and Push Complete Workflow'