apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80 # default port for http clients
      targetPort: {{ .Values.gateway.port }}
  
